# Generated by Django 5.2.17 on 2026-08-12 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_remove_pagetranslation_og_image_url_and_more'),
        ('posts', '0002_post_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(default='content', max_length=50)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('prop_schema', models.JSONField(default=dict)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('props', models.JSONField(default=dict)),
                ('block_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='blocks.blocktype')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='pages.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blocks.pageblock')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
                'indexes': [models.Index(fields=['page', 'parent', 'order'], name='pageblock_tree_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('props', models.JSONField(default=dict)),
                ('block_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='blocks.blocktype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blocks.postblock')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='posts.post')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
                'indexes': [models.Index(fields=['post', 'parent', 'order'], name='postblock_tree_idx')],
            },
        ),
    ]
