# Generated by Django 5.2.17 on 2026-08-13 19:57

from django.db import migrations, models


def migrate_system_to_light(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(theme_preference="system").update(theme_preference="light")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_system_to_light, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=8),
        ),
    ]
