# Generated by Django 5.2.17 on 2026-08-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(unique=True)),
                ('raw_value', models.TextField(db_column='value')),
                ('category', models.CharField(default='general', max_length=50)),
                ('is_secret', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['category', 'key'],
                'permissions': [('manage_settings', 'Can manage site settings')],
            },
        ),
    ]
