# Generated by Django 5.2.17 on 2026-08-12 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
        ('pages', '0002_seed_page_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagetranslation',
            name='og_image_url',
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.media'),
        ),
    ]
