# Generated by Django 5.2.17 on 2026-08-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_pagetranslation_og_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('publish_page', 'Can publish pages')]},
        ),
    ]
