# Generated by Django 5.2.17 on 2026-08-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_pageblock_deleted_at_pageblock_deleted_by_and_more'),
        ('pages', '0004_alter_page_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetype',
            name='allowed_block_types',
            field=models.ManyToManyField(blank=True, related_name='allowed_for_page_types', to='blocks.blocktype'),
        ),
    ]
