# Generated by Django 5.2.17 on 2026-08-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_pagetype_allowed_block_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='background_color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='page',
            name='background_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='page',
            name='container_width',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('default', 'Default'), ('wide', 'Wide'), ('full', 'Full width')], default='default', max_length=20),
        ),
    ]
