# Generated by Django 5.2.17 on 2026-08-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_page_background_color_page_background_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetype',
            name='default_blocks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
